apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: test
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: aws-ebs-csi-driver
  name: ebs-csi-driver-test
  namespace: default
