apiVersion: v1
data:
  accessKey: ""
  account: ""
kind: Secret
metadata:
  labels:
    app: cloud-secret
    app.kubernetes.io/component: cloud-secret
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    kubescape.io/infra: credentials
    tier: ks-control-plane
  name: cloud-secret
  namespace: kubescape
type: Opaque
