apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: openobserve
    app.kubernetes.io/version: v0.80.2
    app.tanka.grafana.com: openobserve
    helm.sh/chart: openobserve-0.80.3
  name: openobserve
  namespace: openobserve
stringData:
  ZO_META_POSTGRES_DSN: postgres://userid:password@host:5432/dbname
  ZO_META_POSTGRES_RO_DSN: ""
  ZO_REPORT_USER_EMAIL: root@example.com
  ZO_REPORT_USER_PASSWORD: Complexpass#123
  ZO_ROOT_USER_EMAIL: root@example.com
  ZO_ROOT_USER_PASSWORD: Complexpass#123
  ZO_ROOT_USER_TOKEN: ""
  ZO_RUM_CLIENT_TOKEN: ""
  ZO_S3_ACCESS_KEY: ""
  ZO_S3_SECRET_KEY: ""
  ZO_SMTP_PASSWORD: +fjlahsguykevfkajvjk#jsbj43$bjkjbkk
  ZO_SMTP_USER_NAME: ABAAQQQQFFFFF
  ZO_TRACING_HEADER_KEY: Authorization
  ZO_TRACING_HEADER_VALUE: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=
type: Opaque
