apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.tanka.grafana.com: openmedia
  name: openmedia
  namespace: openmedia
spec:
  bootstrap:
    initdb:
      database: openmedia
      owner: openmedia-backend
  instances: 3
  postgresql:
    parameters:
      hot_standby_feedback: "on"
      max_slot_wal_keep_size: 10GB
      pgaudit.log: all, -misc
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      sync_replication_slots: "on"
  replicationSlots:
    highAvailability:
      synchronizeLogicalDecoding: true
  storage:
    size: 5Gi
  walStorage:
    size: 1Gi
