apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  labels:
    app.tanka.grafana.com: openmedia
  name: openmedia
  namespace: openmedia
spec:
  cluster:
    name: openmedia
  instances: 3
  pgbouncer:
    parameters:
      max_client_conn: "1000"
    poolMode: session
  type: rw
