apiVersion: v1
data:
  nats.conf: |
    {
      "cluster": {
        "name": "openobserve-nats",
        "no_advertise": true,
        "port": 6222,
        "routes": [
          "nats://openobserve-nats-0.openobserve-nats-headless:6222",
          "nats://openobserve-nats-1.openobserve-nats-headless:6222",
          "nats://openobserve-nats-2.openobserve-nats-headless:6222"
        ]
      },
      "http_port": 8222,
      "jetstream": {
        "max_file_store": 20Gi,
        "max_memory_store": 0,
        "store_dir": "/data"
      },
      "lame_duck_duration": "30s",
      "lame_duck_grace_period": "10s",
      "pid_file": "/var/run/nats/nats.pid",
      "port": 4222,
      "server_name": $SERVER_NAME
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: openobserve
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.11.8
    app.tanka.grafana.com: openobserve
    helm.sh/chart: nats-1.3.13
  name: openobserve-nats-config
  namespace: default
