apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  labels:
    app.tanka.grafana.com: openmedia
    strimzi.io/cluster: openmedia
  name: openmedia-events.profiles.created
  namespace: openmedia
spec:
  partitions: 5
  topicName: events.profiles.created
