apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
    app.tanka.grafana.com: kubearmor
  name: kubearmor-controller-mutating-webhook-configuration
  namespace: kubearmor
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLakNDQWhLZ0F3SUJBZ0lSQUtwdmlFNm1MNWUzdzE5Qmt5RWZKdE13RFFZSktvWklodmNOQVFFTEJRQXcKSHpFZE1Cc0dBMVVFQXhNVWEzVmlaV0Z5Ylc5eUxXTnZiblJ5YjJ4c1pYSXdIaGNOTWpZd05qRTFNVEkwTWpJMQpXaGNOTWprd05qRTBNVEkwTWpJMVdqQWZNUjB3R3dZRFZRUURFeFJyZFdKbFlYSnRiM0l0WTI5dWRISnZiR3hsCmNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUt4MEZIWnRSVWpTcHVlMWJlWDcKRnhrS2gxbnZKbDhGN2RMdEM5MjFRZnUyUjJGV0QwQjdHUFNKMm1jcS9BelQ0K2tjTElZdkdFQXZtSEtRMmNoSgpuRlV1M3pXM1d0U0ZjMnI3ZjNhVE1LYnBFemtock9KTUJaVkhGbHlzazJMMEt3bm5HR212YlJKdWpwbU03ZHBQCmZFd2gvNG9wdlZZL3FnOUZwbzRMN095UU5YckJWRXJNakJRa2FNK056Qks1TlI4UU8wZ1hMV0tGQVZhdHdoeGYKVEljVjRHQ1JQMEcrSysybkgrMndzMHdRNEQ2cVZ1Q3JIWmFrWUhjblk1c25DTzRWL0EvcVFWZ0MxQjJYRmVWeApnNzFwUzZsQjhWVlIwMHk5VENPVGk4aC9xZnkrN0UydTFnREd3emxWaFVvWkcrSEhzQnAvUmRaVUJsY2JHd2FtCnh3TUNBd0VBQWFOaE1GOHdEZ1lEVlIwUEFRSC9CQVFEQWdLa01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUIKQmdnckJnRUZCUWNEQWpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRTSt6WVZ5NWJnQmRSbQpYemk4dWh4T2R3NnlvREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaWNoTXJTM2h3bnNOYTJZQXdESmNkVDFhCnFGUG91Y0J4SE9kSExMVVVGTFFDNFNmNWVYTXZUdjIvaGNTalV4OUxDQVZiV0hZV3lRREdHK3pHZjZCazRIQ2wKb1pjczMvclE2WkozTUR0RTZRdTVkQmZma3VJSTV5TEcxNlRJT0dlL0FqYWhEUUhJSy9jS1p1S0NpZmVzUlVQQQpXN0U0SVIwa3kyOU1OamlLSzdub0JjSm14WlIxV3NNM3pkOHd6eGZnRS9Ndkc0WEd1YVRVQUsvdDkxOXNaTkZxCmgySXhXUW81VE12R0F6djVNTVNYUzVSMUp0K25IRDJXbmNQeXh0M3B1RnV5eGFUZ0gzWXRGeHJoOUs4NjFUd0MKa3FSVVJWWXRuWmZlYWkrTGlUS1YzK0tiRXB0dzd2d0lESmFxN0VvS2l6Y2g0U3oyMHFRRHdhVmxPVER0Snc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: kubearmor-controller-webhook-service
        namespace: kubearmor
        path: /mutate-pods
    failurePolicy: Ignore
    name: annotation.kubearmor.com
    objectSelector:
      matchExpressions:
        - key: kubearmor-app
          operator: DoesNotExist
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
          - pods/binding
        scope: "*"
    sideEffects: NoneOnDryRun
