apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: v1beta1.spdx.softwarecomposition.kubescape.io
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRYkd1dHM0T1hFVTVJYk1vWW9iY2NYVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRHOXlZV2RsTFdOaE1CNFhEVEkyTURZeE16RTJORFUxTTFvWERUSTRNRFl4TWpFMgpORFUxTTFvd0ZURVRNQkVHQTFVRUF4TUtjM1J2Y21GblpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTG54amJLV0ZEbkZ5Y3l5T0g3RzVmWThVSWk1eHJoTVQ5YndzMVJKb0NJQVVPUWwKVzNzc1BMcUFGL0VyaTB3WVg4RjRiSVp6MUhkN1V3NDRIK3JsYXVObXowUXhIYmhvbURNSkt5OStuRDNPUTNBVgpQd1VJdDBvbVZjUlFha2dRMlFjcXZIeURTSEt3VTFTWDFiZ3N5Wjc2bUo3MGlFODRFNUZiaktpYmx5cUtvR3hyCmJzRzB3TlVZVU11d0tqbElVTXE4MStsdU1qVkZJZlBENTRSam5IVHZ4bHlGdXNGTmRyc1g3bEk3UVA2WHA4bXQKV2pnZjhSM2c4N2hLZzhhUDRXUXRScjBiZHM1MlNIc3ZKQ1lnMHJKdDlVdjlzeEg0UllUNmZVMnVOQXZWMXZsNgpZU1Q3RHdBVWhLdXc4c1hCdlNWcVJFK3JqNGFJZytzdll0Q0ovdU1DQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlFVUEhiT3J3WXJKUU83QmM1bExyOUFYRXZrVkRBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFDczlVL05wdzg3ek1FcHphTS93aXh5UUJ2WngwbWc5SklTMXNrUWcyZnJ0cHNWdjBrelV6CjM4aTg3VS90RTRsM1g4Umg0eFRWci84VWhVV1JYU0JLOUVVMVp3WUdYV2V4cDM3RUtnVEpGQ0ZkY09talZKRlMKU1c5TmZNZVJvVENtY0lxcFpvS2R5Ti9kZ2hkSDF1NmhwallWN0tVUmNXYzJRMGo5NmllVFNiRnNWbko1amJhegpnc0YxM0RQZFdZMHhHOXV6L1pYYkxjZVJnblpLZEF3Zms5SElKZ21lQlRxZjIrdThSVjQ5NXVNT1NrbGJMSVIzCmliOUNhRDZsMDdVTUhFWkxEcERNUXNaT0piN053TldZZUFHRlhheSszUkVHT3RKeGVuc2JIS1AwS3dKOWJSTUQKbFdhRnJzL2FUTEMwamRYcUs1S29JOFhlTzJxbVRiS3N4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: spdx.softwarecomposition.kubescape.io
  groupPriorityMinimum: 1000
  service:
    name: storage
    namespace: kubescape
  version: v1beta1
  versionPriority: 15
