apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: v1beta1.spdx.softwarecomposition.kubescape.io
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRVmpDQXdFZVk1U3ppYUhmMzROSk10REFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRHOXlZV2RsTFdOaE1CNFhEVEkyTURZeE5USXlNRGsxTjFvWERUSTRNRFl4TkRJeQpNRGsxTjFvd0ZURVRNQkVHQTFVRUF4TUtjM1J2Y21GblpTMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBS1VMQzRZRWJhQUtNTDk0Ym9HOWJWdEZ3ang1WTN4UnY2U2lLTlVqcFZ3dmJhWWUKOXkyUGV6MWVkaGh6SzZMVEFrZVl5dTFRUFB5cXAyaTJ2ZktaVVlLb1orZXRsRVk2aHoxYlZmQWFlSWVKblUvSwpjTUV5cHgwUEhiQTFacnJiUktRNWZOY2VrakVKb0w4VVpUZTJtL3pWWjlvL0UvQkowblRHaGhxYU1VNHhBRkdyCmN2UzUva1RjZlF1OWtlakwydDJoSmNveE5lbHRBaEVXNC9wODVkMXAzeXd4ektDMVBXMC9LeWlYS0dxV3VlSTAKKytISHRwWGk3a3BGaUl3L2NiRnN3R0lVNDRobmhSNW1nRDlQbHlYQmE4TCt5MzVlbW44SFROQU9OR0swcFQvcgpmSHNZaHZaYUxDRlJLeTFaSFJGcC9yUjFiMForN3FtZm9TMlZlZFVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlFZcEtHQXFiRGUrQ1NZbXJhcUtrVFpsSGxHSnpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFDRnN4YjUyQnRsN3cyV3IxdkNMQ1BieVZjMkhWYjMwbnA5QjZNSGhTSng4SEJQeEh2TDZPCml3OGlxMy9laU1ESGNnNEkyVXFPV1JicDN4U25rY0V4UWxmb3UycVdEMTZ2M1QzME9ZelRUeVp6aUNqQmpSUEUKalFOaFhnbU5wUk1ZdE9oOGh2M0VHRG5JVjVIUC94emR2QjVzdWZxZlljSm9LdzN5c3lCSUFxNnpyYVZZWStPRwpYNkZMWVB6aTVUVE1rWDB4Q3d3cE4yY0R5ZElkUXA3ZkdHeEcyZ0tqTStpbWlqOW1XN2g5QjV4OVNHeEJQeWl5ClZ1SEU5MnhiOUFHaDRjTjYrNUF0M1VuOTMrRHVGR3ZIUmdTY0owK1hMK01TZ3Q2OGkrZmdmb3RaMlMyVFRuSnUKb2cxZHpVOGV0clJqRmpuKzlHRnQzcG1GOVdhVm92bkl1Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: spdx.softwarecomposition.kubescape.io
  groupPriorityMinimum: 1000
  service:
    name: storage
    namespace: kubescape
  version: v1beta1
  versionPriority: 15
