apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: kubescape-admission-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRWHNDSmVlOWs3UzhnVHRtUm1QRUN5REFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13SGhjTk1qWXdOakV6TVRZME5UVXpXaGNOTXpZdwpOakV3TVRZME5UVXpXakFhTVJnd0ZnWURWUVFEREE4cUxtdDFZbVZ6WTJGd1pTNXpkbU13Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURkVkFaOGZneGE3K3lFTlh4RHNEUUtkakxSM1BHRCszNE0KV1BCN1Vud1FEVFBGNDRRR0xNZDlZdEtweE9idmNaSTAzYUllTE14T01TWFRTc0tkdzZXNXBYYldMLzVtYlpTVgpRajVxcE9mdndMSnNZbFVmR0k2Qyt4b1hXZCtoT1ZjTzRXMWJEWUFOUXVQdkgyK2xzb3N6REcwTUVWS1MwekFGCnFGYkpZOEhWNHpHVjJjamdtN3JNMW5YTWdCTGZKSGlxdDhKQ1Q4NGs5NnkwQ09ISG9uL2lzZ1lURGlrRXFDSm4KQkY1cmJMdXcrRkZXODBjRnlsMFJ5bnF1ejVBeHFvSHY4VldySk1YRFZheVRnV2huRXZJeVlvOGFQaURtUkRUVgp4cnE2SnNZSmFqYjUyVC92YmNVKy9VZWZKSkFXaFZEcVRPSUt0MHhsS215eU5sMU04MVRqQWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVY05oZGMwK0xRbVZURXZUSXg1WlpqYlpqVVZndwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQU1pbWFDODFrOVRjYzVuY1dZZ25DM20wdTdGUUpDSFJlSW90dWdlClBYbURSR1BLWDB3YmdNYnY5TmZMQXhFQXVvNHFWUFEvclc3SEg5d1BUOTdtZVFhOGlPUUMvdXRiU2pLTGhQQkQKMHlhbEZCYzlCUys5RXlHbDg5S1JEL0g5RWNjUzB0dExoa3Rtd3BteWtuOG9XQktZRHg2UnJYYWVCV0dlM1JNaQoxYVpwQkIxemlsZys3MlFqSHBZTHJkWDZTMVVDaFRhRnJwRm9kYmE2STIrNnNuYTRYL1poNHIxNlhlSjcxQllOCkc5MjcyYituREhsOW5UaXJQRE5lT2tiSHhVbUticFV5djVGd1djNVdkVFRzRitpTmlXaHdBWTJkT3hVR2x6RDQKWkZveHVuSVpjeUNWMjByS3UxZlBBU3FvYTk0RDZPOGpTZE5PK2xTa0Rqa1ZvV2c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: kubescape-admission-webhook
      namespace: kubescape
      path: /validate
      port: 443
  failurePolicy: Ignore
  name: validation.kubescape.admission
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    - CONNECT
    resources:
    - pods
    - pods/exec
    - pods/portforward
    - pods/attach
    - clusterrolebindings
    - rolebindings
    scope: '*'
  sideEffects: None
