apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    tier: ks-control-plane
  name: kubescape-admission-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lSQVBxSC9LTEFsUWd0Y3Boek5HL0dTRzB3RFFZSktvWklodmNOQVFFTEJRQXcKR2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUI0WERUSTJNRFl4TlRJeU1EazFPRm9YRFRNMgpNRFl4TWpJeU1EazFPRm93R2pFWU1CWUdBMVVFQXd3UEtpNXJkV0psYzJOaGNHVXVjM1pqTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBenp4Qm96WUhMTm1mNWVzU1hpN0VCY0k1QW5BMVEwc1IKZ2xjRXdFSHVHYUdBOEIzV21oTWo3TXdnRnFKSk1GUnh2YmRhMGlVMHo5cnl1MEpxSGIxSTVGSkY1NVd4SWFGRAp5cnRkdmI4VlVjUGtkZWpvbkZhMnozZXRuaWJEZThHbEFBc3VQSStwRnI3bDArSzlvclpkRGJybitmNjh5OTRrCmxoaUo5U1lZdTFrVTU3K1BQUVljY1VhYjAwS05aY2E1VHRLSGkvV09DbzdZM2R5VHZBbG5oMy9ISEY3YUFxTm0KanVJWWpScTRCaklKZkpMNVdkZlVmdHhqWWpzYko4VDhKOVZVR01IamxoSC9YVnhWc1hiTzFhU1BnR1hLUFhTUgpCMkpLNVBUa01xeE9GYnViS3pkTXlScXcwTHRRRC9mZjBveGpTcVQ1cjZsVWpyaWZWSFJMTFFJREFRQUJvMkV3Clh6QU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkJMckNPOHdFR1RoUE5HOGIwOGlETnJLeEpUawpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFNb2NPeDZFN2JBajBvTmIyeDhEcW1IenhjdHlsTHZGczZxN2FFCmFJSUdJY2QrYnlXTStLTmQvcTRwR1dPRHlURWtNdFU5VjRrU0JXRk5Ia2h0QUVBMU05c1dQWUg0d3BiNFdPd0MKcVRmMmZaS09XcDlranJOZkxMTDg0cnZ0VzAzM1VHNjZOUlhoTEsyT1lmWmkvNk1ER0JiUUxSSDIvOHhzY2h5cQp5RFBoa3M2UDF6RStIRGJ2aFEvTTEzWWU4a0N0RlhVdlRvODdtZko1TjRZNWFmTFpxbENmUVhxejhIWTdycGF4CmI0eGEyRGlGY1AvSHhiOUpCZFlGbDN4dnNrYlI5NUdmQ1VId3dTVVJjTUxHNU04U3NBUDd1cEtZUE1QelJRUGMKU1l1djhSaHVweWtObWIrcmloZkhja1NiRHdBNm4xeXNSQ2xkSTFidUxlNlVwTklBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: kubescape-admission-webhook
        namespace: kubescape
        path: /validate
        port: 443
    failurePolicy: Ignore
    name: validation.kubescape.admission
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
          - CONNECT
        resources:
          - pods
          - pods/exec
          - pods/portforward
          - pods/attach
          - clusterrolebindings
          - rolebindings
        scope: "*"
    sideEffects: None
