apiVersion: v1
data:
  config.json: |
    {
      "excludeNamespaces": "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public",
      "namespace": "kubescape",
      "triggersecurityframework": true,
      "podScanGuardTime": "1h",
      "excludeJsonPaths":null,
      "nodeAgentAutoscaler": {
        "enabled": false,
        "nodeGroupLabel": "node.kubernetes.io/instance-type",
        "resourcePercentages": {
          "requestCPU": 2,
          "requestMemory": 2,
          "limitCPU": 5,
          "limitMemory": 5
        },
        "minResources": {
          "cpu": "100m",
          "memory": "600Mi"
        },
        "maxResources": {
          "cpu": "2000m",
          "memory": "4Gi"
        },
        "reconcileInterval": "5m",
        "templatePath": "/etc/templates/daemonset-template.yaml",
        "operatorDeploymentName": "operator",
        "goMemLimitPercentage": 0.8
      }
    }
kind: ConfigMap
metadata:
  labels:
    app: operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    kubescape.io/tier: core
    tier: ks-control-plane
  name: operator
  namespace: kubescape
