apiVersion: v1
data:
  config.json: |
    {
      "cleanupInterval": "6h",
      "disableVirtualCRDs": false,
      "disableSeccompProfileEndpoint": true,
      "excludeJsonPaths": null,
      "defaultQueueLength": 100,
      "defaultWorkerCount": 2,
      "defaultMaxObjectSize": 400000,
      "queueManagerEnabled": true,
      "kindQueues": {"applicationprofiles":{"maxObjectSize":20000000,"queueLength":50,"workerCount":2},"containerprofiles":{"maxObjectSize":2500000,"queueLength":50,"workerCount":2},"networkneighborhoods":{"maxObjectSize":10000000,"queueLength":50,"workerCount":2},"openvulnerabilityexchangecontainers":{"maxObjectSize":500000,"queueLength":50,"workerCount":1},"sbomsyftfiltereds":{"maxObjectSize":50000000,"queueLength":50,"workerCount":1},"sbomsyfts":{"maxObjectSize":100000000,"queueLength":50,"workerCount":1},"vulnerabilitymanifests":{"maxObjectSize":50000000,"queueLength":50,"workerCount":1}},
      "tlsClientCaFile": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
      "tlsServerCertFile": "/etc/storage-ca-certificates/tls.crt",
      "tlsServerKeyFile": "/etc/storage-ca-certificates/tls.key",
      "serverBindPort": "8443"
    }
kind: ConfigMap
metadata:
  labels:
    app: storage
    app.kubernetes.io/component: storage
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    app.kubernetes.io/version: 1.40.2
    app.tanka.grafana.com: kubescape
    helm.sh/chart: kubescape-operator-1.40.2
    kubescape.io/ignore: "true"
    kubescape.io/tier: core
    tier: ks-control-plane
  name: storage
  namespace: kubescape
